<a href="https://colab.research.google.com/github/FrancoPalavicinoG/cellia/blob/main/notebooks/08_preprocessing_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Load DF from Google Drive

Mount Drive

In [105]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Import libraries

In [106]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

Load Dataframe

In [107]:
input_path = "/content/drive/MyDrive/cellia_drive/Datasets/"

df = pd.read_excel(input_path + "bio_dataset.xlsx")

In [108]:
print("Dataset shape:", df.shape)

Dataset shape: (5214, 32)

Dataset example

In [109]:
display(df.head(10))

,SEQN,GENDER,AGE_YEARS,AGE_MONTHS,BODY_MASS_INDEX,HEIGHT,WEIGHT,TOTAL_CHOL,CHOLESTEROL,CREATININE,...,HEART_FAILURE_AGE,CORO_HEART_DISEASE_AGE,ANGINA_PECTORIS_AGE,HEART_ATTACK_AGE,STROKE_AGE,HEART_ATTACK_RELATIVES,SMOKING,ALCOHOL,ACTIVE_1,ACTIVE_2
0,73557,1,69,828,26.7,171.3,78.3,167,168.0,1.21,...,0,0,0,0,62,0,0.000000,1.000000,2.600000,4.200000
1,73558,1,54,648,28.6,176.8,89.5,170,167.0,0.79,...,0,0,0,0,0,0,1.000000,0.800000,3.600000,3.800000
2,73559,1,72,864,28.9,175.3,88.9,126,127.0,1.22,...,0,0,0,0,0,1,0.000000,1.000000,3.600000,1.000000
3,73561,0,73,876,19.7,162.4,52.0,201,207.0,0.73,...,0,0,0,0,0,1,0.468972,0.459701,3.307826,3.485977
4,73562,1,56,672,41.7,158.7,105.0,226,230.0,0.89,...,0,54,0,55,0,0,0.000000,1.000000,2.600000,4.200000
5,73564,0,61,732,35.7,161.8,93.4,168,167.0,0.92,...,0,0,0,0,0,0,0.600000,1.000000,2.800000,5.200000
6,73566,0,56,672,26.5,152.8,61.8,278,278.0,0.55,...,0,0,0,0,0,0,1.000000,0.800000,3.600000,3.800000
7,73567,1,65,780,22.0,172.4,65.3,173,170.0,0.97,...,0,0,0,0,0,1,1.000000,0.800000,3.600000,3.800000
8,73568,0,26,312,20.3,152.5,47.1,168,174.0,0.74,...,0,0,0,0,0,0,0.600000,0.400000,3.800000,4.000000
9,73571,1,76,912,34.4,172.5,102.4,167,157.0,1.19,...,0,0,0,72,0,0,0.800000,1.000000,2.000000,2.000000

### Heart condition indicator (HCI)

In [110]:
heart_condition_cols = [
    'HEART_FAILURE',
    'CORO_HEART_DISEASE',
    'ANGINA_PECTORIS',
    'HEART_ATTACK',
    'STROKE'
]

In [111]:
df['HEART_CONDITION'] = (df[heart_condition_cols].sum(axis=1) > 0).astype(int)

In [112]:
display(df.head(5))

,SEQN,GENDER,AGE_YEARS,AGE_MONTHS,BODY_MASS_INDEX,HEIGHT,WEIGHT,TOTAL_CHOL,CHOLESTEROL,CREATININE,...,CORO_HEART_DISEASE_AGE,ANGINA_PECTORIS_AGE,HEART_ATTACK_AGE,STROKE_AGE,HEART_ATTACK_RELATIVES,SMOKING,ALCOHOL,ACTIVE_1,ACTIVE_2,HEART_CONDITION
0,73557,1,69,828,26.7,171.3,78.3,167,168.0,1.21,...,0,0,0,62,0,0.000000,1.000000,2.600000,4.200000,1
1,73558,1,54,648,28.6,176.8,89.5,170,167.0,0.79,...,0,0,0,0,0,1.000000,0.800000,3.600000,3.800000,0
2,73559,1,72,864,28.9,175.3,88.9,126,127.0,1.22,...,0,0,0,0,1,0.000000,1.000000,3.600000,1.000000,0
3,73561,0,73,876,19.7,162.4,52.0,201,207.0,0.73,...,0,0,0,0,1,0.468972,0.459701,3.307826,3.485977,0
4,73562,1,56,672,41.7,158.7,105.0,226,230.0,0.89,...,54,0,55,0,0,0.000000,1.000000,2.600000,4.200000,1

In [113]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5214 entries, 0 to 5213
Data columns (total 33 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SEQN                    5214 non-null   int64
 1   GENDER                  5214 non-null   int64
 2   AGE_YEARS               5214 non-null   int64
 3   AGE_MONTHS              5214 non-null   int64
 4   BODY_MASS_INDEX         5214 non-null   float64
 5   HEIGHT                  5214 non-null   float64
 6   WEIGHT                  5214 non-null   float64
 7   TOTAL_CHOL              5214 non-null   int64
 8   CHOLESTEROL             5214 non-null   float64
 9   CREATININE              5214 non-null   float64
 10  TRIGLYCERIDES_R         5214 non-null   float64
 11  LDL                     5214 non-null   float64
 12  TRIGLYCERIDE            5214 non-null   float64
 13  HDL                     5214 non-null   int64
 14  GLUCOSE                 5214 non-null   float64
 15  HYPERTENSION            5214 non-null   int64
 16  HIGH_CHOLESTEROL        5214 non-null   int64
 17  HEART_FAILURE           5214 non-null   int64
 18  CORO_HEART_DISEASE      5214 non-null   int64
 19  ANGINA_PECTORIS         5214 non-null   int64
 20  HEART_ATTACK            5214 non-null   int64
 21  STROKE                  5214 non-null   int64
 22  HEART_FAILURE_AGE       5214 non-null   int64
 23  CORO_HEART_DISEASE_AGE  5214 non-null   int64
 24  ANGINA_PECTORIS_AGE     5214 non-null   int64
 25  HEART_ATTACK_AGE        5214 non-null   int64
 26  STROKE_AGE              5214 non-null   int64
 27  HEART_ATTACK_RELATIVES  5214 non-null   int64
 28  SMOKING                 5214 non-null   float64
 29  ALCOHOL                 5214 non-null   float64
 30  ACTIVE_1                5214 non-null   float64
 31  ACTIVE_2                5214 non-null   float64
 32  HEART_CONDITION         5214 non-null   int64
dtypes: float64(13), int64(20)
memory usage: 1.3 MB
None

## Preprocessing

Drop irrelevant columns

In [114]:
cols_to_drop = [
    'AGE_MONTHS', 'SEQN',
    'TRIGLYCERIDES_R', 'HEART_FAILURE',
    'CORO_HEART_DISEASE','ANGINA_PECTORIS',
    'HEART_ATTACK', 'STROKE', 'TRIGLYCERIDE',
    'HEART_FAILURE_AGE', 'CORO_HEART_DISEASE_AGE',
    'ANGINA_PECTORIS_AGE', 'HEART_ATTACK_AGE', 'STROKE_AGE',
    'CHOLESTEROL'
]

In [115]:
df_preprocess = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

### Categorical Dataset

In [117]:
print(df_preprocess.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5214 entries, 0 to 5213
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   GENDER                  5214 non-null   int64
 1   AGE_YEARS               5214 non-null   int64
 2   BODY_MASS_INDEX         5214 non-null   float64
 3   HEIGHT                  5214 non-null   float64
 4   WEIGHT                  5214 non-null   float64
 5   TOTAL_CHOL              5214 non-null   int64
 6   CREATININE              5214 non-null   float64
 7   LDL                     5214 non-null   float64
 8   HDL                     5214 non-null   int64
 9   GLUCOSE                 5214 non-null   float64
 10  HYPERTENSION            5214 non-null   int64
 11  HIGH_CHOLESTEROL        5214 non-null   int64
 12  HEART_ATTACK_RELATIVES  5214 non-null   int64
 13  SMOKING                 5214 non-null   float64
 14  ALCOHOL                 5214 non-null   float64
 15  ACTIVE_1                5214 non-null   float64
 16  ACTIVE_2                5214 non-null   float64
 17  HEART_CONDITION         5214 non-null   int64
dtypes: float64(10), int64(8)
memory usage: 733.3 KB
None

In [118]:
display(df_preprocess.head(5))

,GENDER,AGE_YEARS,BODY_MASS_INDEX,HEIGHT,WEIGHT,TOTAL_CHOL,CREATININE,LDL,HDL,GLUCOSE,HYPERTENSION,HIGH_CHOLESTEROL,HEART_ATTACK_RELATIVES,SMOKING,ALCOHOL,ACTIVE_1,ACTIVE_2,HEART_CONDITION
0,1,69,26.7,171.3,78.3,167,1.21,91.065171,65,125.945215,1,1,0,0.000000,1.000000,2.600000,4.200000,1
1,1,54,28.6,176.8,89.5,170,0.79,87.387310,50,124.696180,1,1,0,1.000000,0.800000,3.600000,3.800000,0
2,1,72,28.9,175.3,88.9,126,1.22,56.000000,60,126.151344,1,1,1,0.000000,1.000000,3.600000,1.000000,0
3,0,73,19.7,162.4,52.0,201,0.73,101.000000,85,123.728065,1,0,1,0.468972,0.459701,3.307826,3.485977,0
4,1,56,41.7,158.7,105.0,226,0.89,119.628631,38,159.236039,1,1,0,0.000000,1.000000,2.600000,4.200000,1

In [119]:
df_clean = df_preprocess.copy()

# === GENDER ===
# 0 = female, 1 = male
df_clean["GENDER"] = df_clean["GENDER"].astype(int)

# === AGE_YEARS ===
df_clean["AGE_YEARS"] = df_clean["AGE_YEARS"].astype(int)

# === BODY MASS INDEX CATEGORICAL ===
def bmi_category(bmi):
    if bmi < 18.5:
        return 0  # underweight
    elif bmi < 25:
        return 1  # normal
    elif bmi < 30:
        return 2  # overweight
    else:
        return 3  # obese

df_clean["BMI"] = df_clean["BODY_MASS_INDEX"].apply(bmi_category)
df_clean.drop(columns=["BODY_MASS_INDEX"], inplace=True)

# === HEIGHT & WEIGHT  ===
df_clean["HEIGHT"] = df_clean["HEIGHT"].astype(float)
df_clean["WEIGHT"] = df_clean["WEIGHT"].astype(float)

# === CHOLESTEROL ===
df_clean["CHOL_CATEGORY"] = pd.cut(
    df_clean["TOTAL_CHOL"],
    bins=[0, 200, 239, 279, np.inf],
    labels=[0, 1, 2, 3],               # 0=Normal, 1=Above Normal, 2=Well Above Normal, 3=High
    include_lowest=True
).astype(int)
df_clean.drop(columns=["TOTAL_CHOL"], inplace=True)

# === LDL CATEGORY ===
bins=[0, 100, 159, np.inf]
df_clean["LDL_CATEGORY"] = np.digitize(df_clean["LDL"], bins, right=False)
df_clean.drop(columns=["LDL"], inplace=True)

# === HDL CATEGORY ===
bins = [0, 40, 59, np.inf]
df_clean["HDL_CATEGORY"] = np.digitize(df_clean["HDL"], bins, right=False)
df_clean.drop(columns=["HDL"], inplace=True)

# === GLUCOSE CATEGORY ===
df_clean["GLUCOSE_CATEGORY"] = pd.cut(
    df_clean["GLUCOSE"],
    bins=[0, 100, 125, np.inf],
    labels=[1, 2, 3]
).astype(int)
df_clean.drop(columns=["GLUCOSE"], inplace=True)

# === binary vars ===
binary_vars = [
    "HYPERTENSION", "HIGH_CHOLESTEROL",
    "HEART_ATTACK_RELATIVES"
]
for var in binary_vars:
    df_clean[var] = df_clean[var].astype(int)

# === SMOKING & ALCOHOL ===
df_clean["SMOKING_BINARY"] = (df_clean["SMOKING"] > 0.5).astype(int)
df_clean["ALCOHOL_BINARY"] = (df_clean["ALCOHOL"] > 0.5).astype(int)

df_clean.drop(columns=["SMOKING", "ALCOHOL"], inplace=True)

# === ACTIVITY ===
df_clean["ACTIVE"] = ((df_clean["ACTIVE_1"] > 4) | (df_clean["ACTIVE_2"] > 2)).astype(int)
df_clean.drop(columns=["ACTIVE_1", "ACTIVE_2"], inplace=True)


# === CREATININE ===
def categorize_creatinine(row):
    if row["GENDER"] == 1:  # male
        if row["CREATININE"] < 0.74:
            return 1  # low
        elif row["CREATININE"] <= 1.35:
            return 2  # normal
        else:
            return 3  # high
    else:  # female
        if row["CREATININE"] < 0.59:
            return 1
        elif row["CREATININE"] <= 1.04:
            return 2
        else:
            return 3

df_clean["CREATININE_CATEGORY"] = df_clean.apply(categorize_creatinine, axis=1)
df_clean.drop(columns=["CREATININE"], inplace=True)

# === Target ===
df_clean["HEART_CONDITION"] = df_clean["HEART_CONDITION"].astype(int)

In [120]:
df_clean = df_clean.rename(columns={
    "AGE_YEARS": "AGE",
    "CHOL_CATEGORY": "CHOLESTEROL",
    "HDL_CATEGORY": "HDL",
    "LDL_CATEGORY": "LDL",
    "GLUCOSE_CATEGORY": "GLUCOSE",
    "SMOKING_BINARY": "SMOKING",
    "ALCOHOL_BINARY": "ALCOHOL",
    "CREATININE_CATEGORY": "CREATININE",
})

In [121]:
print(df_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5214 entries, 0 to 5213
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   GENDER                  5214 non-null   int64
 1   AGE                     5214 non-null   int64
 2   HEIGHT                  5214 non-null   float64
 3   WEIGHT                  5214 non-null   float64
 4   HYPERTENSION            5214 non-null   int64
 5   HIGH_CHOLESTEROL        5214 non-null   int64
 6   HEART_ATTACK_RELATIVES  5214 non-null   int64
 7   HEART_CONDITION         5214 non-null   int64
 8   BMI                     5214 non-null   int64
 9   CHOLESTEROL             5214 non-null   int64
 10  LDL                     5214 non-null   int64
 11  HDL                     5214 non-null   int64
 12  GLUCOSE                 5214 non-null   int64
 13  SMOKING                 5214 non-null   int64
 14  ALCOHOL                 5214 non-null   int64
 15  ACTIVE                  5214 non-null   int64
 16  CREATININE              5214 non-null   int64
dtypes: float64(2), int64(15)
memory usage: 692.6 KB
None

In [122]:
column_order = [
    "GENDER", "AGE", "HEIGHT", "WEIGHT", "BMI",
    "CHOLESTEROL", "LDL", "HDL", "GLUCOSE", "CREATININE",
    "HYPERTENSION", "HIGH_CHOLESTEROL", "SMOKING", "ALCOHOL", "ACTIVE",
    "HEART_ATTACK_RELATIVES", "HEART_CONDITION"
]

df_clean = df_clean[column_order]

In [123]:
display(df_clean.head(5))

,GENDER,AGE,HEIGHT,WEIGHT,BMI,CHOLESTEROL,LDL,HDL,GLUCOSE,CREATININE,HYPERTENSION,HIGH_CHOLESTEROL,SMOKING,ALCOHOL,ACTIVE,HEART_ATTACK_RELATIVES,HEART_CONDITION
0,1,69,171.3,78.3,2,0,1,3,3,2,1,1,0,1,1,0,1
1,1,54,176.8,89.5,2,0,1,2,2,2,1,1,1,1,1,0,0
2,1,72,175.3,88.9,2,0,1,3,3,2,1,1,0,1,0,1,0
3,0,73,162.4,52.0,1,1,2,3,2,2,1,0,0,0,1,1,0
4,1,56,158.7,105.0,3,1,2,1,3,2,1,1,0,1,1,0,1

### Feature Engineering

In [124]:
def create_feature_engineering(df):
    df = df.copy()

    # Normalizations
    df['AGE_NORMALIZED'] = (df['AGE'] - df['AGE'].min()) / (df['AGE'].max() - df['AGE'].min())

    # Age groups
    df['AGE_GROUP'] = pd.cut(
        df['AGE'], bins=[0, 45, 55, 65, np.inf],
        labels=['<45', '45-55', '55-65', '65+']
    )

    df['AGE_RISK_EXPONENTIAL'] = np.where(df['AGE'] > 45,
        np.exp((df['AGE'] - 45) / 10), 1.0
    )

    # Metabolic features
    df['METABOLIC_PROFILE'] = df['CHOLESTEROL'] / df['AGE']

    df['METABOLIC_RISK_SCORE'] = (
        (df['CHOLESTEROL'] > 1).astype(int) +
        (df['GLUCOSE'] > 1).astype(int) +
        (df['LDL'] > 1).astype(int)
    )

    df['CHOL_CATEGORY'] = pd.cut(
        df['CHOLESTEROL'],
        bins=[-1, 0, 1, 2, 1000],
        labels=['Normal', 'Above Normal', 'Well Above Normal', 'High'],
        include_lowest=True
    )
    # Gender interaction
    df['MALE_AGE_INTERACTION'] = df['GENDER'] * df['AGE']

    df['FEMALE_CHOL_INTERACTION'] = (1 - df['GENDER']) * df['CHOLESTEROL']

    df['GENDER_SPECIFIC_RISK'] = np.where(
        df['GENDER'] == 1,
        df['AGE'] * 0.1 + df['CHOLESTEROL'] * 0.005,
        df['CHOLESTEROL'] * 0.008
    )

    # Risk scores
    df['TRADITIONAL_RISK_SCORE'] = (
        (df['AGE']) * 0.05 +
        (df['GENDER'] * 10) +
        ((df['CHOLESTEROL'] - 1) * 25) +
        (df['GLUCOSE'] * 20)
    )

    df['COMBINED_RISK_SCORE'] = (
        df['TRADITIONAL_RISK_SCORE'] * 0.6 +
        df['METABOLIC_RISK_SCORE'] * 0.4
    )


    # Categorical encodings
    encoding_categories = {
        'AGE_GROUP': ['<45', '45-55', '55-65', '65+'],
        'CHOL_CATEGORY': ['Normal', 'Above Normal', 'Well Above Normal', 'High']
    }

    for col, categories in encoding_categories.items():
        df[f'{col}_ENCODED'] = pd.Categorical(df[col], categories=categories).codes

    return df

In [125]:
engineered_df = create_feature_engineering(df_clean)

In [127]:
display(engineered_df.head(5))

,GENDER,AGE,HEIGHT,WEIGHT,BMI,CHOLESTEROL,LDL,HDL,GLUCOSE,CREATININE,...,METABOLIC_PROFILE,METABOLIC_RISK_SCORE,CHOL_CATEGORY,MALE_AGE_INTERACTION,FEMALE_CHOL_INTERACTION,GENDER_SPECIFIC_RISK,TRADITIONAL_RISK_SCORE,COMBINED_RISK_SCORE,AGE_GROUP_ENCODED,CHOL_CATEGORY_ENCODED
0,1,69,171.3,78.3,2,0,1,3,3,2,...,0.000000,1,Normal,69,0,6.900,48.45,29.47,3,0
1,1,54,176.8,89.5,2,0,1,2,2,2,...,0.000000,1,Normal,54,0,5.400,27.70,17.02,1,0
2,1,72,175.3,88.9,2,0,1,3,3,2,...,0.000000,1,Normal,72,0,7.200,48.60,29.56,3,0
3,0,73,162.4,52.0,1,1,2,3,2,2,...,0.013699,2,Above Normal,0,1,0.008,43.65,26.99,3,1
4,1,56,158.7,105.0,3,1,2,1,3,2,...,0.017857,2,Above Normal,56,0,5.605,72.80,44.48,2,1

In [128]:
print(engineered_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5214 entries, 0 to 5213
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   GENDER                   5214 non-null   int64
 1   AGE                      5214 non-null   int64
 2   HEIGHT                   5214 non-null   float64
 3   WEIGHT                   5214 non-null   float64
 4   BMI                      5214 non-null   int64
 5   CHOLESTEROL              5214 non-null   int64
 6   LDL                      5214 non-null   int64
 7   HDL                      5214 non-null   int64
 8   GLUCOSE                  5214 non-null   int64
 9   CREATININE               5214 non-null   int64
 10  HYPERTENSION             5214 non-null   int64
 11  HIGH_CHOLESTEROL         5214 non-null   int64
 12  SMOKING                  5214 non-null   int64
 13  ALCOHOL                  5214 non-null   int64
 14  ACTIVE                   5214 non-null   int64
 15  HEART_ATTACK_RELATIVES   5214 non-null   int64
 16  HEART_CONDITION          5214 non-null   int64
 17  AGE_NORMALIZED           5214 non-null   float64
 18  AGE_GROUP                5214 non-null   category
 19  AGE_RISK_EXPONENTIAL     5214 non-null   float64
 20  METABOLIC_PROFILE        5214 non-null   float64
 21  METABOLIC_RISK_SCORE     5214 non-null   int64
 22  CHOL_CATEGORY            5214 non-null   category
 23  MALE_AGE_INTERACTION     5214 non-null   int64
 24  FEMALE_CHOL_INTERACTION  5214 non-null   int64
 25  GENDER_SPECIFIC_RISK     5214 non-null   float64
 26  TRADITIONAL_RISK_SCORE   5214 non-null   float64
 27  COMBINED_RISK_SCORE      5214 non-null   float64
 28  AGE_GROUP_ENCODED        5214 non-null   int8
 29  CHOL_CATEGORY_ENCODED    5214 non-null   int8
dtypes: category(2), float64(8), int64(18), int8(2)
memory usage: 1.1 MB
None

#### Split data

Imports

In [129]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from imblearn.over_sampling import SMOTE
import pandas as pd

Types of features

In [130]:
numeric_features = [
    "AGE", "HEIGHT", "WEIGHT",
    "AGE_NORMALIZED",
    "AGE_RISK_EXPONENTIAL",
    "METABOLIC_PROFILE",
    "GENDER_SPECIFIC_RISK",
    "TRADITIONAL_RISK_SCORE",
    "COMBINED_RISK_SCORE",
    "MALE_AGE_INTERACTION",
    "FEMALE_CHOL_INTERACTION"
]

categorical_features = [
    "BMI", "CHOLESTEROL", "LDL",
    "HDL", "GLUCOSE", "CREATININE",
    "AGE_GROUP_ENCODED", "CHOL_CATEGORY_ENCODED"
]

binary_features = [
    "GENDER", "HYPERTENSION", "HIGH_CHOLESTEROL",
    "SMOKING", "ALCOHOL", "ACTIVE", "HEART_ATTACK_RELATIVES"
]

target = ["HEART_CONDITION"]

final_columns = numeric_features + categorical_features + binary_features + target
df_final = engineered_df[final_columns].copy()

Numeric variables scalling

In [131]:
scaler = StandardScaler()
df_final[numeric_features] = scaler.fit_transform(df_final[numeric_features])

OneHot codification for categories

In [72]:
# encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
# encoded_cats = encoder.fit_transform(df_final[categorical_features])
# encoded_df = pd.DataFrame(
#     encoded_cats,
#     columns=encoder.get_feature_names_out(categorical_features)
# )

Merge all

In [73]:
# df_ready = pd.concat(
#     [df_final[numeric_features + binary_features], encoded_df, df_final[target]],
#     axis=1
# )

In [132]:
print("✅ Dataset ready to split:")
print(df_final.head())
print(f"\nFinal Shape: {df_final.shape}")

✅ Dataset ready to split:
        AGE    HEIGHT    WEIGHT  AGE_NORMALIZED  AGE_RISK_EXPONENTIAL  \
0  1.157711  0.412171 -0.145572        1.157711              0.625941
1  0.295956  0.952128  0.362307        0.295956             -0.376408
2  1.330062  0.804867  0.335099        1.330062              1.077343
3  1.387512 -0.461577 -1.338178        1.387512              1.260513
4  0.410857 -0.824821  1.065174        0.410857             -0.312668

   METABOLIC_PROFILE  GENDER_SPECIFIC_RISK  TRADITIONAL_RISK_SCORE  \
0          -0.616666              1.683344                0.379832
1          -0.616666              1.131471               -0.388162
2          -0.616666              1.793718                0.385383
3           0.177500             -0.852325                0.202175
4           0.418586              1.206894                1.281068

   COMBINED_RISK_SCORE  MALE_AGE_INTERACTION  ...  AGE_GROUP_ENCODED  \
0             0.362355              1.684005  ...                  3
1            -0.393769              1.132313  ...                  1
2             0.367821              1.794344  ...                  3
3             0.211738             -0.853779  ...                  3
4             1.273956              1.205872  ...                  2

   CHOL_CATEGORY_ENCODED  GENDER  HYPERTENSION  HIGH_CHOLESTEROL  SMOKING  \
0                      0       1             1                 1        0
1                      0       1             1                 1        1
2                      0       1             1                 1        0
3                      1       0             1                 0        0
4                      1       1             1                 1        0

   ALCOHOL  ACTIVE  HEART_ATTACK_RELATIVES  HEART_CONDITION
0        1       1                       0                1
1        1       1                       0                0
2        1       0                       1                0
3        0       1                       1                0
4        1       1                       0                1

[5 rows x 27 columns]

Final Shape: (5214, 27)

In [133]:
X = df_final.drop(columns=['HEART_CONDITION'])
y = df_final['HEART_CONDITION']

#### Split data 70:15:15

In [134]:
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, stratify=y, random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42
)

### Manage Label distrbution via Undersampling

In [144]:
unique, counts = np.unique(y_train, return_counts=True)
print(dict(zip(unique, counts)))

minority_count = counts[1]
majority_target = int(minority_count * (60 / 40))  # 60/40 ratio
print(f"Goal: {majority_target} in class 0.")

{np.int64(0): np.int64(3290), np.int64(1): np.int64(359)}
Goal: 538 in class 0.

In [146]:
from imblearn.under_sampling import RandomUnderSampler

sampling_strategy = {0: majority_target, 1: minority_count}

rus = RandomUnderSampler(sampling_strategy=sampling_strategy, random_state=42)

X_train_res, y_train_res = rus.fit_resample(X_train, y_train)

print("Original distribution:", dict(zip(unique, counts)))
print("Distribution after undersampling:", dict(zip(*np.unique(y_train_res, return_counts=True))))

Original distribution: {np.int64(0): np.int64(3290), np.int64(1): np.int64(359)}
Distribution after undersampling: {np.int64(0): np.int64(538), np.int64(1): np.int64(359)}

#### Save preprocessed datasets

Save datasets

In [147]:
output_path = "/content/drive/MyDrive/cellia_drive/Datasets/"

In [148]:
X_train_res.to_csv(output_path + "X_train_cat.csv", index=False)
y_train_res.to_csv(output_path + "y_train_cat.csv", index=False)

X_val.to_csv(output_path + "X_val_cat.csv", index=False)
y_val.to_csv(output_path + "y_val_cat.csv", index=False)

X_test.to_csv(output_path + "X_test_cat.csv", index=False)
y_test.to_csv(output_path + "y_test_cat.csv", index=False)

In [149]:
X_train_res.shape

(897, 26)

In [150]:
print("✅ Files saved:")
print(f"   - {output_path}X_train_cat.csv")
print(f"   - {output_path}y_train_cat.csv")
print(f"   - {output_path}X_val_cat.csv")
print(f"   - {output_path}y_val_cat.csv")
print(f"   - {output_path}X_test_cat.csv")
print(f"   - {output_path}y_test_cat.csv")

✅ Files saved:
   - /content/drive/MyDrive/cellia_drive/Datasets/X_train_cat.csv
   - /content/drive/MyDrive/cellia_drive/Datasets/y_train_cat.csv
   - /content/drive/MyDrive/cellia_drive/Datasets/X_val_cat.csv
   - /content/drive/MyDrive/cellia_drive/Datasets/y_val_cat.csv
   - /content/drive/MyDrive/cellia_drive/Datasets/X_test_cat.csv
   - /content/drive/MyDrive/cellia_drive/Datasets/y_test_cat.csv